from typing import *

DB_NAME = 'database.sqlite'
DB_MEMO = ':memory:'

TYPE_INT = 'INTEGER'
TYPE_FLOAT = 'REAL'
TYPE_STRING = 'TEXT'
TYPE_BYTE = 'BLOB'
TYPE_NULL = 'NULL'
TYPE_BOOL = TYPE_INT

CREATE_TABLE = 'CREATE TABLE IF NOT EXISTS'
CREATE_VIEW = 'CREATE VIEW IF NOT EXISTS'
CREATE_TRIGGER = 'CREATE TRIGGER IF NOT EXISTS'
CREATE_UNIQUE_INDEX = 'CREATE UNIQUE INDEX IF NOT EXISTS'
# CREATE_PROC = 'CREATE PROC IF NOT EXISTS'

PKEY = 'PRIMARY KEY'
NOT_NULL = 'NOT NULL'
UNIQUE = 'UNIQUE'
REF = 'REFERENCES'
CHECK = 'CHECK'
IS_COLOR = "REGEXP '^#([A-Fa-f0-9]{6})$'"
ENFORCE_FOREIGN_KEY = 'PRAGMA foreign_keys = ON;'

ON_UPDATE = 'ON UPDATE'
ON_DELETE = 'ON DELETE'

NO_ACTION = 'NO ACTION'
RESTRICT = 'RESTRICT'
SET_NULL = 'SET NULL'
DEFAULT = 'DEFAULT'
CASCADE = 'CASCADE'

TABLE_USERS = 'tbl_users'
TABLE_PERMISSIONS = 'tbl_permissions'
TABLE_PERMISSION_VIEW = 'tbl_permission_view'
TABLE_PERMISSION_EDIT = 'tbl_permission_edit'
TABLE_SITES = 'tbl_sites'
TABLE_UNITS = 'tbl_units'
TABLE_NETS = 'tbl_nets'
TABLE_MARKS = 'tbl_marks'
TABLE_PAKAL_META = 'tbl_pakal_metadata'

VIEW_PAKAL = 'view_pakal'
VIEW_PERMISSION_VIEW = 'view_permission_view'
VIEW_PERMISSION_EDIT = 'view_permission_edit'
